# Generated by Django 4.2.20 on 2025-09-03 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='registro',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número da aula dentro do dia (1ª, 2ª, 3ª...).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Registro/Aula do dia'),
        ),
        migrations.AddConstraint(
            model_name='frequencia',
            constraint=models.UniqueConstraint(fields=('aluno', 'data', 'disciplina', 'registro'), name='unique_frequencia_aluno_dia_disciplina_registro'),
        ),
    ]
