# Generated by Django 4.2.20 on 2025-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_featureblock_herocontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureBlock',
        ),
        migrations.DeleteModel(
            name='HeroContent',
        ),
    ]
