# Generated by Django 4.2.20 on 2025-05-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_featureblock_delete_herocontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('pode_gerenciar_escola', 'Pode gerenciar toda a escola'), ('pode_gerenciar_turmas', 'Pode gerenciar turmas e alunos'), ('pode_lancar_notas', 'Pode lançar notas e frequências'), ('pode_ver_boletim', 'Pode visualizar boletim')]},
        ),
    ]
