# Generated by Django 4.2.20 on 2025-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('ti-book', 'Livro'), ('ti-blackboard', 'Quadro'), ('ti-agenda', 'Agenda'), ('ti-write', 'Escrever')], default='ti-book', max_length=50, verbose_name='Ícone')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Bloco de Recurso',
                'verbose_name_plural': 'Blocos de Recursos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(verbose_name='Subtítulo')),
                ('button_text', models.CharField(max_length=50, verbose_name='Texto do Botão')),
                ('button_link', models.CharField(default='#', max_length=200, verbose_name='Link do Botão')),
            ],
            options={
                'verbose_name': 'Conteúdo do Hero',
                'verbose_name_plural': 'Conteúdo do Hero',
            },
        ),
    ]
