# Generated by Django 4.2.20 on 2025-05-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEducenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sobre o Educenter', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Texto principal sobre o Educenter', verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, help_text='Marque para exibir esta seção no site', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sobre o Educenter',
                'verbose_name_plural': 'Sobre o Educenter',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(help_text='Texto que descreve a missão da empresa', verbose_name='Nossa Missão')),
                ('is_active', models.BooleanField(default=True, help_text='Marque para exibir esta seção no site', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sobre Nós',
                'verbose_name_plural': 'Sobre Nós',
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Texto que aparecerá com o checkbox', verbose_name='Texto do item')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição dos itens', verbose_name='Ordem')),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='site_admin.abouteducenter')),
            ],
            options={
                'verbose_name': 'Item de Característica',
                'verbose_name_plural': 'Itens de Característica',
                'ordering': ['order'],
            },
        ),
    ]
