# Generated by Django 4.2.20 on 2025-05-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureBlock',
        ),
        migrations.DeleteModel(
            name='HeroContent',
        ),
    ]
